### ISSUE TITLE
Groups.csv is missing

### ISSUE THREAD

**Issue by korpx** [przybylskirobert/ADSecurity#3]
Following https://www.azureblog.pl/2020/04/13/deploying-tiering/

Groups.csv is missing.
Object with samaccountname=ServiceDeskOperators is missing.

**Comment by przybylskirobert** [comment]
Dear Korpx. 
from the moment when I published the article, there were 2 modifications in the scripts: Groups.csv file has been renamed to AdminGroups.csv
Regarding the ServiceDeskOperators  group it has been also renamed to Tier2ServiceDeskOperators
